### ISSUE TITLE
[Bug] Fails to start on 2022.12

### ISSUE THREAD

**Issue by dannytsang** [Vaskivskyi/ha-chroma#38]
### The problem

I get the following error message since upgrading to Home Assistant 2022.12.0:
```
The following integrations and platforms could not be set up:

[chroma](https://github.com/Vaskivskyi/ha-chroma) ([Show logs](https://6bb95oy22xmx2gw48v5x25gomyn4veh9.ui.nabu.casa/config/logs?filter=chroma))
Please check your config and [logs](https://6bb95oy22xmx2gw48v5x25gomyn4veh9.ui.nabu.casa/config/logs).
```
![image](https://user-images.githubusercontent.com/567982/206855250-f8cc6b2c-5f57-4b81-8e9e-18893c1d4dc8.png)

### Firmware version

?

### Integration version with the issue

0.2.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.12.0

### Is there anything useful in the logs?

```txt
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 12:27:30 (3 occurrences)
Last logged: 12:27:34

Unable to install package aiochroma==0.1.1: ERROR: Cannot install aiochroma==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
```

```
Logger: homeassistant.setup
Source: setup.py:202
First occurred: 12:27:34 (1 occurrences)
Last logged: 12:27:34

Setup failed for custom integration chroma: Requirements for chroma not found: ['aiochroma==0.1.1'].
```

### Additional information

Sorry, not sure where I find the ChromaSDK version and there's no instructions that I could see in the about or bug reporting page.

**Comment by KSPSlice** [comment]
Same here. Coincided with the update to 2022.12 of HA.
Setup failed for custom integration chroma: Requirements for chroma not found: ['aiochroma==0.1.1'].
11:45:28 AM – (ERROR) setup.py
Unable to install package aiochroma==0.1.1: ERROR: Cannot install aiochroma==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
11:45:28 AM – (ERROR) util/package.py - message first occurred at 11:45:15 AM and shows up 3 times

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the delay.

Please, check the integration with HA version 2022.12.3 or higher.

Unfortunately, HA is implementing some "improvements", which they later anyway revert.

**Comment by dannytsang** [comment]
@Vaskivskyi yes it's working again. Thank you.
